
import '../../styles/globals.css'
import Header from '@app/components/Header'


export const metadata = {
  title: 'gorillasproduction',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
   <Header />
        {children}
     
      
        </body>
    </html>
  )
}
